version: '3.2'
services:
  backend:
    image: server
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - WATCHPACK_POLLING = "true"
  frontend:
    image: frontend
    stdin_open : true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - WATCHPACK_POLLING = "true"
